default: &default
  adapter: postgresql
  username: pandu
  password: password
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: digital_shop

test:
  <<: *default
  database: digital_shop_test
