default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: digital_shop

test:
  <<: *default
  database: digital_shop

production:
  <<: *default
  database: digital_shop
  username: 
  password: 
